# Generated by Django 4.2 on 2023-04-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('fle_id', models.CharField(max_length=100)),
                ('is_fle', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=1000)),
                ('prompt', models.CharField(max_length=500, null=True)),
                ('is_true_prompt', models.BooleanField(default=False)),
                ('is_last_message', models.BooleanField(default=False)),
                ('chat_duration', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
